site_name: Idgeo Blog & Ressourcerie
site_url: https://thomasidgeo.github.io/idgeo_blog
theme:
  language: fr
  name: material
  font:
    text : Merriweather Sans
    code: Red Hat Mono
  logo: assets/Globe.png
  favicon: assets/favicon.ico
  features:
    - content.tooltips
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toogle:
        icon: material/wea
        name: Thème Sombre
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toogle:
        icon: material/weather-night
        name: Thème Clair
      primary: green
      accent: deep orange

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ThomasIdgeo
    - icon: fontawesome/solid/paper-plane
      link: mailto:thomas.michel@idgeo.fr

