site_name: Idgeo Blog & Ressourcerie
site_url: https://thomasidgeo.github.io/idgeo_blog
theme:
  language: fr
  name: material
  font:
    text : Merriweather Sans
    code: Red Hat Mono
  logo: assets/Globe.png
  favicon: assets/favicon.ico
  features:
    - content.tooltips
    - navigation.footer
  extra_css:
  - stylesheets/extra.css

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue
      accent: indigo

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: blue
      accent: indigo
  
extra_css:
  - stylesheets/extra.css

plugins:
  - blog

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ThomasIdgeo
    - icon: fontawesome/solid/paper-plane
      link: mailto:thomas.michel@idgeo.fr

